### PR TITLE
fix n+1 problem for zoom account availability

### LINKED ISSUE #18: [ZoomAccounts] Fix N+1 issue in availability field
To improve the performance of the query by reducing the no. of separate db queries. Need to batch the availability status check queries in [zoomAccount.availability](https://github.com/coding-blocks/gondor/blob/master/api/graphql/query/ZoomAccount/availability.js). 

Problem: [N+1](https://engineering.shopify.com/blogs/engineering/solving-the-n-1-problem-for-graphql-through-batching)
Solution: [Dataloader](https://www.npmjs.com/package/dataloader)
Learn: https://www.youtube.com/watch?v=OQTnXNCDywA

### PR DESCRIPTION
**Pull request by prabalsingh24**
fixes #18

### CODE REVIEW

File: api/services/ZoomAccount/index.js [hunk 1]
```diff
@@ -9,23 +10,31 @@ export default class ZoomAccount extends BaseModelService {
...
   @requireInstance
-  ifAvailableDuring(dateTimeRange, options) {
-    return ZoomAccount.findAvailaibilityDuring(
-      this.instance.id,
+  async ifAvailableDuring(dateTimeRange, options) {
+    const key = {
+      id: this.instance.id,
       dateTimeRange,
       options,
-    );
```
Comment (prabalsingh24) [inline api/services/ZoomAccount/index.js]: Should this be ` ...options `

Comment (prabalsingh24) [reply api/services/ZoomAccount/index.js]: I will remove the key and pass it as params as you mentioned in other PR

Comment (0xnmn) [reply api/services/ZoomAccount/index.js]: Yes, you need to spread the options. Good catch.

**Comment by 0xnmn** [comment]
@prabalsingh24 you need to add separate loader for Resource.availability.

File: api/graphql/query/Resource/availability.js [hunk 2]
```diff
@@ -10,17 +10,20 @@ class ZoomAccountAvailability extends BaseResolver {
...
+        await ZoomAccount.findAllAvailabilityDuring([
+          {
+            id: this.parent.subject_id,
+            dateTimeRange: {
+              start_at: topic.start_at,
+              end_at: topic.end_at,
+            },
+            excludeTopics: [topic.id],
+          },
+        ])
```
Comment (prabalsingh24) [inline api/graphql/query/Resource/availability.js]: @hereisnaman  Do you mean this?

```
await this.ctx.loaders.zoomAccountAvailabilityLoader.load({
      id: this.parent.id,
      dateTimeRange: {
        start_at: topic.start_at,
        end_at: topic.end_at,
      },
      excludeTopics: [topic.id]
    })
```

File: api/routes/graphql/index.js [hunk 3]
```diff
@@ -3,10 +3,16 @@ import connect from 'Utils/connect';
...
+import ZoomAccount from 'Services/ZoomAccount';
 
 const server = new ApolloServer({
   schema,
-  context: ({ req }) => ({ viewer: req.viewer }),
+  context: ({ req }) => ({
+    viewer: req.viewer,
+    loaders: {
+      zoomAccountAvailabilityLoader: ZoomAccount.getAvailabilityLoader(),
+    },
```
Comment (prabalsingh24) [inline api/routes/graphql/index.js]: or do you mean to add a different loader here.

Comment (prabalsingh24) [reply api/routes/graphql/index.js]: `zoomAccountResourceLoader` something like this?

File: api/services/ZoomAccount/index.js [hunk 4]
```diff
@@ -10,22 +11,33 @@ export default class ZoomAccount extends BaseModelService {
...
-    });
+  static async findAllAvailabilityDuring(keys) {
+    return Promise.all(
+      keys.map(
+        async ({ id, ...args }) =>
+          !(await Models.ZoomAccount.findOne({
+            where: { id },
+            ...utilizedResourceClause(args),
+          })),
+      ),
```
Comment (0xnmn) [inline api/services/ZoomAccount/index.js]: Defeats the purpose when you are still making N db calls for N items.

**Review by 0xnmn — CHANGES_REQUESTED** [review]

File: api/graphql/query/Resource/availability.js (hunk 2 above)
Comment (0xnmn) [reply api/graphql/query/Resource/availability.js]: Yes but before that lets fix the main issue .

File: api/graphql/query/Resource/availability.js [hunk 5]
```diff
@@ -10,17 +10,18 @@ class ZoomAccountAvailability extends BaseResolver {
...
-        {
+    if (this.parent.subject_type === 'ZoomAccount') {
+      return await this.ctx.loaders.zoomAccountAvailability.load({
+        id: this.parent.id,
+        dateTimeRange: {
           start_at: topic.start_at,
           end_at: topic.end_at,
         },
-        {
+        options: {
```
Comment (0xnmn) [inline api/graphql/query/Resource/availability.js]: simply pass excludeTopics, no need to nest inside options.

File: api/services/ZoomAccount/index.js [hunk 6]
```diff
@@ -10,22 +11,35 @@ export default class ZoomAccount extends BaseModelService {
...
+    const { id, ...args } = keys[0];
+    return Models.ZoomAccount.findAll({
+      where: {
+        id: {
+          [Models.Sequelize.Op.in]: keys.map(({ id }) => id),
+        },
+      },
+      ...utilizedResourceClause(args.dateTimeRange, args.options),
+    }).then((accounts) =>
+      keys.map((key) => !accounts.find((account) => key.id === account.id)),
```
Comment (0xnmn) [inline api/services/ZoomAccount/index.js]: can't compare just based on id. Need to do deep equate for the whole key.

File: api/services/ZoomAccount/index.js [hunk 7]
```diff
@@ -10,22 +11,35 @@ export default class ZoomAccount extends BaseModelService {
...
-  static async findAvailaibilityDuring(id, ...args) {
-    const data = await Models.ZoomAccount.findOne({
-      where: { id },
-      ...utilizedResourceClause(...args),
-    });
+  static async findAllAvailabilityDuring(keys) {
+    const { id, ...args } = keys[0];
+    return Models.ZoomAccount.findAll({
+      where: {
+        id: {
```
Comment (0xnmn) [inline api/services/ZoomAccount/index.js]:
```javascript
where {
  [Models.Sequelize.Op.or]: keys.map( (id, dateTimeRange, ...options) => ({
    id,
    ...utilizedResourceClause(dateTimeRange, options)
  })),
}
```

File: api/services/ZoomAccount/index.js (hunk 6 above)
Comment (0xnmn) [reply api/services/ZoomAccount/index.js]: use https://www.npmjs.com/package/deep-equal

File: api/services/ZoomAccount/index.js [hunk 8]
```diff
@@ -10,22 +11,35 @@ export default class ZoomAccount extends BaseModelService {
     return Models.ZoomAccount.findAll(utilizedResourceClause(...args));
   }
 
-  static async findAvailaibilityDuring(id, ...args) {
-    const data = await Models.ZoomAccount.findOne({
-      where: { id },
-      ...utilizedResourceClause(...args),
-    });
```
Comment (0xnmn) [inline api/services/ZoomAccount/index.js]: No need to remove this.

File: api/services/ZoomAccount/index.js [hunk 9]
```diff
@@ -10,22 +11,35 @@ export default class ZoomAccount extends BaseModelService {
...
+    return new DataLoader(this.findAllAvailabilityDuring);
   }
 
   @requireInstance
-  ifAvailableDuring(dateTimeRange, options) {
-    return ZoomAccount.findAvailaibilityDuring(
-      this.instance.id,
-      dateTimeRange,
-      options,
-    );
```
Comment (0xnmn) [inline api/services/ZoomAccount/index.js]: No need to change this.

**Review by 0xnmn — CHANGES_REQUESTED** [review]

**Comment by 0xnmn** [comment]
Please update your branch with master.

File: api/services/ZoomAccount/index.js (hunk 6 above)
Comment (prabalsingh24) [reply api/services/ZoomAccount/index.js]:
```
key : {
  id: 28,
  dateTimeRange: {
    start_at: '2020-05-20T18:30:00.000Z',
    end_at: '2020-05-20T19:30:00.000Z'
  }
}
```

```
zoomAccount : {
    id: 28,
    email: 'Davis@gmail.com',
    created_at: 2020-05-21T06:45:50.203Z,
    updated_at: 2020-05-21T06:45:50.203Z

}
```

Comment (prabalsingh24) [reply api/services/ZoomAccount/index.js]: I don't think we can do deep equate here?

File: api/services/ZoomAccount/index.js (hunk 7 above)
Comment (prabalsingh24) [reply api/services/ZoomAccount/index.js]: You probably mean this right (destruct key)
```
where {
  [Models.Sequelize.Op.or]: keys.map( ({id, dateTimeRange, ...options}) => ({
    id,
    ...utilizedResourceClause(dateTimeRange, options)
  })),
}
```

But this also is not working. Probably because `include` do not come in `where` ?

**Comment by prabalsingh24** [comment]
I have few doubts. I've replied in above comments :)

File: api/services/ZoomAccount/index.js (hunk 7 above)
Comment (prabalsingh24) [reply api/services/ZoomAccount/index.js]: `dateTimeRange` and `options` will be same for all the keys right (because they are describing that one event only)?

We did something similar to this here too **[calender-event-invite-status](https://github.com/coding-blocks/gondor/blob/3775f05141b6cf5041f36cd00e0df3ddfc7cf867/api/services/CalendarEventInvite/index.js#L64)**

Comment (0xnmn) [reply api/services/ZoomAccount/index.js]: You don't know if the dateTimeRange will be same or not. There we named it ViewerCalendarEventInviteStatus to reflect that it is for the viewer thus the user_id is same for all.

Comment (0xnmn) [reply api/services/ZoomAccount/index.js]: My bad, yeah they will be 2 differ things. but have similar Or logic for the where clause on the first model and the where clause inside the include.

File: api/services/ZoomAccount/index.js (hunk 6 above)
Comment (0xnmn) [reply api/services/ZoomAccount/index.js]: You also get ZoomAccount.resource having start_at and end_at. Form the same shape with the data from db and then equate them.

**Review by 0xnmn — CHANGES_REQUESTED** [review]

**Comment by 0xnmn** [comment]
@prabalsingh24 what is the status on this?

**Comment by prabalsingh24** [comment]
> @prabalsingh24 what is the status on this?

Sir can we discuss this over a call once?

**Comment by prabalsingh24** [comment]
I've made the changes and it is working too. Have a look whenever you're free :)


Sorry I was little slow in doing this, I had my end semester exams

File: api/services/ZoomAccount/Loaders/Availability.js [hunk 10]
```diff
@@ -0,0 +1,64 @@
...
+      ],
+    });
+
+    return this.keys.map(
+      (key) =>
+        !accounts.find((account) => this.equateKeyAndInvite(key, account)),
+    );
+  };
+
+  equateKeyAndInvite({ id, excludedEvents = [], dateTimeRange }, account) {
```
Comment (0xnmn) [inline api/services/ZoomAccount/Loaders/Availability.js]: You are not equating key to invite here. Fix the name.

**Review by 0xnmn — CHANGES_REQUESTED** [review]

**Comment by 0xnmn** [comment]
Looks good. Just minor change request.

**Review by 0xnmn — APPROVED** [review]
